default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: rails  
  host: postgres # This is the docker-compose service name
  port: 5432
  timeout: 5000


development:
  <<: *default
  database: app_development