version: "3.9"

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    ports: 
      - '5432:5432'
    volumes:
      - rails-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - rails-redis:/var/lib/redis/data

  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
    # volumes:
    #   - rails:/opt/app
    command: ["bundle","exec","puma"]
    ports:
      - '3000:3000'

volumes:
  rails-postgres:
  rails-redis:
  rails: