version: "3.9"

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    ports: 
      - '5432:5432'
    volumes:
      - rails-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - rails-redis:/var/lib/redis/data
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 5

  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
    image: rails:latest
    volumes:
      - rails:/app
    #command: ["bundle","exec","puma"]
    command: ["/bin/bash","-c","rails server -b 0.0.0.0"]
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  rails-postgres:
  rails-redis:
  rails: