services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    ports: 
      - '5433:5432'
    volumes:
      - rails-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - rails-redis:/var/lib/redis/data
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 5

  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
    image: rails:latest
    volumes:
      - rails:/app
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_REGION}
    command: ["/bin/bash","-c","rails server -b 0.0.0.0"]
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  rails-postgres:
  rails-redis:
  rails: